const PacketType = {
	GET_CONNECTED_USERS: 0,
	GET_SEARCH_RESULT: 1,
	GET_PLAYLIST: 2,
	
	DOWNLOAD_BY_ID: 200,
	ADD_TO_PLAYLIST: 201,
	UPDATE_NICKNAME: 202,
	PLAY_AUDIO: 203,
	SKIP_AUDIO: 204,
};

export default PacketType;
