const PacketType = {
	GET_CONNECTED_USERS: 0,
	GET_SEARCH_RESULT: 1,
	FILE_PACKET: 2,
	GET_PLAYLIST: 3,
	DOWNLOAD_BY_ID: 200,
	ADD_TO_PLAYLIST: 201,
	UPDATE_NICKNAME: 202
};

export default PacketType;
